### ISSUE TITLE
Autoembedding doesn't works with relative path images

### ISSUE THREAD

**Issue by ircop** [molteber/puz-autoembed#1]
When image url begins from site root, embedding doesn't work
Example: <img src="/images/123.jpg">

Error: Swift_IoException: Unable to open file for reading [/images/mail/7/60dd3059.png]

It might make sense to use public_path( $src ) if substr( $src, 0, 1 ) == '/'

**Comment by molteber** [comment]
Hmm, thats not good.
I can think of two solution:
1. Use $_SERVER to grab hostname and scheme and prepend that before the url if ut contains / as first character.
2. Add a function_exists call with public_path so that Laravel users gets the fix.

Cons with the last one is that its only Laravel which gets the fix.
Pros, they get the fix and the package is mainly for Laravel as well.

Cons with the first one, $_SERVER can be tampered with 
Pros the fix might work for both swiftmailer and leave users.

On the other hand, I could  introduce a setting which explicit defines the root path for the relative paths.

**Comment by ircop** [comment]
1. Use $_SERVER to grab hostname and scheme and prepend that before the url if ut contains / as first character.
2. Add a function_exists call with public_path so that Laravel users gets the fix.

:))
Yes, i'm already preparing pull request with thos changes ;) Will be ready in 5 mins.

**Comment by molteber** [comment]
But what do you think about the last one? Giving it a setting so define the path it should use in that situation? 

I have to make some configuration anyway later for when storing the images (data imgages).

**Comment by ircop** [comment]
I think that this option is excessive, if script is running with web SAPI.

But it might be useful if script is running from cli, and it's not in laravel environment (where we have public_path() )

p.s. sorry for my bad english

**Comment by ircop** [comment]
I've made pull request with changes in embedImage function

**Comment by ircop** [comment]
#2

**Comment by molteber** [comment]
I'll take a look at it :) Thanks for contributing!

**Comment by molteber** [comment]
Sorry I'm a bit late here. I merged the commits now :)
